apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/nfs
    server: nfsxxxxx
    fsType: ext4

# ahora estamos especificando una configuración nfs de ruta
# con la ruta así como la dirección del servidor

