apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  spec:
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    capacity:
      storage: 1Gi

 # este PersistentVolume es simplemente un tipo hostPatht en el nodo trabajador que ejecuta su Pod.
