apiVersion: v1
kind: Service
metadata:
  name: daemon-headless
spec:
  selector:
    app: nginx-daemon
    env: test
  clusterIP: None
  ports:
    - port: 3011
      protocol: TCP
      targetPort: 80