apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-10T01:51:18Z"
  labels:
    app: hello-minikube
  name: hello-minikube
  namespace: default
  resourceVersion: "4107"
  uid: d568d323-b243-4685-bf9b-b8b71d059ddc
spec:
  clusterIP: 10.109.207.47
  clusterIPs:
  - 10.109.207.47
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30459
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-minikube
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
