apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  # ClusterIP conecta nuestros pods internamente
  type: ClusterIP
  ports:
  - port: 80 # El port expuesto por el servicio
    protocol: TCP
    targetPort: 80 # El puerto de destino en los pods
  selector:
    run: nginx-clusterip
