# Create cluster
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  # permiten que el ingress controller se ejecute en nodos específicos que coincidan con el selector de etiquetas
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # permite que el host local realice solicitudes al controlador de Ingress a través de los puertos 80/443
  extraPortMappings:
  - containerPort: 80
    hostPort: 800
    protocol: TCP
  - containerPort: 443
    hostPort: 4430
    protocol: TCP

# cmd after create cluster
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
# kt port-forward services/name-svc 3000:3000
