apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-connect
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: client-svc
            port:
              # Default port used by the image
              number: 3002

