apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-example
spec:
  # crea un volume que la app y el sidecar compartan
  volumes:
  - name: shared-logs
    emptyDir: {}

  containers:
  # el container del sidecar
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo  $(date -u) 'This is just an echo from simple Sidecar Container' >> /var/log/index.html; sleep 5;done"]
    resources: {}
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  # la app container principal
  - name: main-container
    # Simple application: nginx serving on the port 80 that takes the index.html
    # from the volume mount workdir location
    image: nginx
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default

