apiVersion: batch/v1
kind: CronJob
metadata:
  name: hi-k8s
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: hi-k8s
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: ["date echo 'Hello from the Kubernetes cluster'"]

