apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-pv-hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/yosoy/Kubernetes/volumes/pv2/test
