# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "liveness-http"
  namespace: probe
  labels:
    app: "liveness-http"
spec:
  containers:
  - name: liveness-http
    image: "registry.k8s.io/liveness"
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: "Awesome"
      initialDelaySeconds: 3
      periodSeconds: 3
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
---

