apiVersion: v1
kind: Pod
metadata:
  annotations:
    team: flexbeauty
  labels:
    env: dev
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - containerPort: 80
