apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec: 
  containers:
  - name: nginx-container
    image: nginx
  - name: busybox-container
    image: busybox:latest
  - name: fod-container
    image: fod:1.0
