apiVersion: v1
kind: Pod
metadata: 
  name: pod-several-env-secret 
  namespace: default 
spec:
  containers:
   - name: nginx-container
     image: nginx:latest
     envFrom:
     - secretRef:
         name: mysecret # Name of the secret object
  
# este pod va implementar un secret
# envFrom clave YAML. 
# Al usar esta clave, leerá todos los valores de un Secreto y 
# los obtendrá como variables de entorno en el Pod, 
