apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
  namespace: default
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      env:
      - name: PASS_ENV # name env
        valueFrom:
          secretKeyRef:
            name: mypassword # name of secret object
            key: pass # name of key in secret object
