apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
spec:
  volumes:
  - name: my-secret-volume
    secret:
      secretName: secret-for-volume
  containers:
  - name: nginx-container 
    image: nginx:latest
    volumeMounts:
    - name: my-secret-volume
      mountPath: /etc/password-mounted-path
